version: '4.23.0'

services:
  db:
    image: postgres:16
    networks:
      - my-network
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: pgpwd4habr
    ports:
      - '5434:5432'
  AuthDB:
    image: redis:7.2.1
    networks:
      - my-network
    depends_on:
      - db
  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - AuthDB
    networks:
      - my-network
    environment:
      AUTH_DB_HOST: redis://AuthDB:6379
      POSTGRES_USER: user_user
      DB_HOST: db
      POSTGRES_PASSWORD: pgpwd4habr
      DB_DB: finansialSystemDB
      DB_PORT: 5434
    volumes:
      - postgres_db:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  postgres_db:
