version: '3.8'

services:
  postgres:
    hostname: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'finansialSystemDB'
      POSTGRES_USER: 'user_user'
      POSTGRES_PASSWORD: 'pgpwd4habr'
    ports:
      - '5432:5432'
    volumes:
      - ./my-custom-pg-hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./db/postgres/dbPG.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - some-network

  app:
    image: alesiapekarchik/financeadvisor
    container_name: financeadvisor
    build: .
    ports:
      - '${APP_PORT}:${APP_PORT}'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - some-network

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - '6379:6379'
    networks:
      - some-network

networks:
  some-network: {}
