version: '2.23.0'

services:
  db:
    image: postgres:16
    networks:
      - my-network
    environment:
      POSTGRES_DB: finansialSystemDB
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: pgpwd4habr
    ports:
      - '5432:5432'
  AuthDB:
    image: redis:7.2.1
    networks:
      - my-network
    depends_on:
      - db
  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - AuthDB
      - db
    networks:
      - my-network
    env_file:
      - .env.example
    volumes:
      - postgres_db:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  postgres_db:
